default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>

development:
  <<: *default
  database: career_pilot_development

test:
  <<: *default
  database: career_pilot_test

production:
  <<: *default
  database: career_pilot_production
  username: career_pilot
  password: <%= ENV["CAREER_PILOT_DATABASE_PASSWORD"] %>
